### ISSUE TITLE
.bashrc references mobisec

### ISSUE THREAD

**Issue by flamableconcrete** [santoku/Santoku-Linux#12]
There are still references to /opt/mobisec in the .bashrc file.  Probably want to update those!

**Comment by thomascannon** [comment]
Thank you for reporting! The first Alpha release was a quick fork of MobiSec so I could release the tool I was presenting about at Defcon 20 (which runs on Santoku). So there are still a number of references still in there. The upcoming release has been built from scratch so won't have these issues. I'm going to leave this issue open until the new release ships in case we get multiple such reports.
