### ISSUE TITLE
Android Brute Force Script Line Endings

### ISSUE THREAD

**Issue by santoku** [santoku/Santoku-Linux#4]
In Santoku, when you try to run, for example, the Android brute force without prefacing python, you get:

": No such file or directory"

This is because the script is in DOS format…if you change to Unix \r, it works fine

**Comment by thomascannon** [comment]
For now, if you run "python bruteforce_stdcrypto.py" it will run fine. Fixing the line endings will allow it to work without typing python.

**Comment by tfernandes** [comment]
You can also use dos2unix to convert the file and get rid of those annoying DOS \r. 

Or even do this: 

> cd /opt/santoku/forensics/
> tr -d '\r' < bruteforce_stdcrypto.py  > bruteforce_stdcrypto2.py (or something similar if you don't want to create a new file)
> chmod +x bruteforce_stdcrypto2.py
