### ISSUE TITLE
Initial Password

### ISSUE THREAD

**Issue by kswartz** [santoku/Santoku-Linux#8]
When installing santoku for the first time, the password input during the install process doesn't take. The first login to Santoku after a full install reverts back to "santoku" instead.

**Comment by Ashnayr** [comment]
Just installed 0.5 and facing the same issue except "santoku" also is not working.

**Comment by Cybersloth** [comment]
username santoku + password blank worked for me

**Comment by bcheeves** [comment]
Hi, I just wanted to mention that, as a first time user, the out of the box experience is not working so well in this case. I had to dig around to find the FAQ, which had the incorrect password.  Username santoku + blank password (as @Cybersloth mentioned). It should be in the documentation under the "HOW TO"'s for installation.  

https://santoku-linux.com/howtos/

**Comment by KooshaYeganeh** [comment]
username santoku and password in blank
